// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lubdwiodoiydrhqthtbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1YmR3aW9kb2l5ZHJocXRodGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NTA5MDksImV4cCI6MjA1MjQyNjkwOX0.X2DBGdOgioq4ARPMTdpPlCu6Qw_QgeajmDRijWpp4B0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);